### ISSUE TITLE
require lib/lineFunctions when file's name is linefunctions

### ISSUE THREAD

**Issue by elidoran** [kmalakoff/node-semvers#1]
https://github.com/kmalakoff/node-semvers/blob/59b5b29120ab0d0aacceb304a270b6b48dfa825c/index.js#L8

[lib folder has linefunctions.js](https://github.com/kmalakoff/node-semvers/tree/master/lib)

**Comment by kmalakoff** [comment]
Thank you for reporting this. It is fixed now.
